version: "3.8"
name: "edge-store-backend"

services:
  postgres:
    image: postgres:alpine3.19
    container_name: edge-store-backend-postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
    - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env

volumes:
  db_data:
